### ISSUE TITLE
multipart form data is no longer automatically set

### ISSUE THREAD

**Issue by leonbloy** [bmuenzenmeyer/axios-1.0.0-migration-guide#5]
This got me after migrating from 0.27.2 to 1.5

https://github.com/axios/axios/issues/5556

I'm not sure when it changed

In Axios ,  a request which includes a formData payload as in 

```
const formData = new FormData()
formData.append("sample", "sample")

axiosInstance({
   url: "inventories",
   method: "post",
   data: formData,
 },

```

will automatically include the  header 'Content-Type': 'multipart/form-data'.

Previously, that happened even if a  'Content-Type': 'application/json' was set.

Now (after 1.x ?), in that case, Axios will serialize FormData/HTMLForm object to JSON.

**Comment by bmuenzenmeyer** [comment]
thanks @leonbloy !
