### ISSUE TITLE
`paramsSerializer` option can be a function again, as of v1.3.5

### ISSUE THREAD

**Issue by drichar** [bmuenzenmeyer/axios-1.0.0-migration-guide#6]
Anyone migrating from v0.x to v1.3.5 or later will not have to change `paramsSerializer` functions. Perhaps a note can be added to https://github.com/bmuenzenmeyer/axios-1.0.0-migration-guide#paramsserializer-shape-changes

See:
https://github.com/axios/axios/releases/tag/v1.3.5
https://github.com/axios/axios/pull/5633
https://github.com/axios/axios/commit/a56c8661209d5ce5a645a05f294a0e08a6c1f6b3

**Comment by bmuenzenmeyer** [comment]
thanks @drichar !
